#!/bin/bash

# If user passes 1, then just compile, otherwise watch

if [[ $# == 1 ]]; then
  sass sass/xcombined.scss:site.css --style compressed
else
  # No minification
  #sass --watch sass/xcombined.scss:site.css --style expanded

  sass --watch sass/xcombined.scss:site.css --style compressed
fi

exit 0
