#!/bin/bash

# If user passes 1, then just compile, otherwise watch

if [[ $# == 1 ]]; then
  sass css/sass/xcombined.scss:css/style.css --style compressed
else
  # No minification
  #sass --watch css/sass/xcombined.scss:css/style.css --style expanded

  sass --watch css/sass/xcombined.scss:css/style.css --style compressed
fi

exit 0
